In [359]:
import numpy as np
import matplotlib.pyplot as plt
import json

In [360]:
%ls

Untitled.ipynb         words_dictionary.json


# Load dictionary

In [361]:
direc = 'words_dictionary.json'
with open(direc, 'r') as f:
  data = json.load(f)

# Find all five letter words

In [362]:
# list(data.keys())[-1] last element of dict
five_letter = []
for i in data:
    if(len(i)==5):
        five_letter.append(i)
print("Total 5 letter words: ",len(five_letter))

Total 5 letter words:  15918


In [364]:
five_letter

['aahed',
 'aalii',
 'aargh',
 'aaron',
 'abaca',
 'abaci',
 'aback',
 'abada',
 'abaff',
 'abaft',
 'abaka',
 'abama',
 'abamp',
 'aband',
 'abase',
 'abash',
 'abask',
 'abate',
 'abaue',
 'abave',
 'abaze',
 'abbas',
 'abbey',
 'abbes',
 'abbie',
 'abbot',
 'abdal',
 'abdat',
 'abdom',
 'abeam',
 'abear',
 'abede',
 'abele',
 'abend',
 'aberr',
 'abets',
 'abhor',
 'abide',
 'abidi',
 'abies',
 'abyes',
 'abilo',
 'abime',
 'abysm',
 'abyss',
 'abkar',
 'abler',
 'ables',
 'ablet',
 'ablow',
 'abmho',
 'abner',
 'abnet',
 'abode',
 'abody',
 'abohm',
 'aboil',
 'aboma',
 'aboon',
 'abord',
 'abort',
 'abote',
 'about',
 'above',
 'abray',
 'abram',
 'abret',
 'abrim',
 'abrin',
 'abris',
 'abrus',
 'absee',
 'absey',
 'absis',
 'absit',
 'abstr',
 'abuna',
 'abune',
 'abura',
 'abuse',
 'abush',
 'abuta',
 'abuts',
 'abuzz',
 'abwab',
 'acale',
 'acana',
 'acapu',
 'acara',
 'acari',
 'acast',
 'acate',
 'accel',
 'accoy',
 'accra',
 'accts',
 'accum',
 'accur',
 'accus',
 'acedy',


# Generate a state vector for all the words

In [159]:
lett_mat = np.zeros((len(five_letter),26))

cnt = 0
for i in five_letter:
    for j in i:
        #print(j,ord(j)-97,cnt)
        lett_mat[cnt,ord(j)-97] += 1
    cnt+=1
    
[state,count] = np.unique(lett_mat,return_counts=True,axis=0)
count_dres_arg = np.argsort(count)[::-1]
state_des = state[count_dres_arg] #states in descending order of prob
print("Max count: ",count[count_dres_arg[0]])
print("Corresponding state ",state[count_dres_arg[0]])

Max count:  14
Corresponding state  [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0.
 0. 0.]


# Analysis of "orthogonality" of words with decreasing probability

In [344]:
a = []
cnt = 0
for i in lett_mat:
    if(np.all(i==state_des[0])):
        a.append(cnt)
    cnt+=1
print("Printing all the words corresponding to the most probable state")
for k in a:
    print(five_letter[k])

Printing all the words corresponding to the most probable state
apers
apres
asper
pares
parse
pears
prase
presa
rapes
reaps
repas
spaer
spare
spear


In [345]:
dot_states = (np.dot(state_des,state_des[0,:].reshape(26,1))).reshape(state.shape[0])

cnt0 = 0
cnt1 = 0
cnt2 = 0
for i in range(state.shape[0]):
    if (dot_states[i] == 0 and cnt0==0):
        print("Closest index with dot product 0 = ", i)
        cnt0+=1
    if (dot_states[i] == 1 and cnt1==0):
        print("Closest index with dot product 1 = ", i)
        cnt1+=1

    if (dot_states[i] == 2 and cnt2==0):
        print("Closest index with dot product 2 = ", i)
        cnt2+=1

Closest index with dot product 2 =  5
Closest index with dot product 1 =  42
Closest index with dot product 0 =  394


In [354]:
def print_words(five_letters,state_des,dot_val,index):
    a = []
    cnt = 0
    for i in lett_mat:
        if(np.all(i==state_des[index])):
            a.append(cnt)
        cnt+=1
    print("Printing all the words corresponding dot prod =",dot_val)
    for k in a:
        print(five_letter[k])
        
        
print_words(five_letter,state_des,2,5)
print_words(five_letter,state_des,1,42)
print_words(five_letter,state_des,0,394)


Printing all the words corresponding dot prod = 2
agron
angor
argon
garon
goran
grano
groan
nagor
orang
organ
rogan
ronga
Printing all the words corresponding dot prod = 1
cions
coins
cosin
icons
oscin
scion
sonic
Printing all the words corresponding dot prod = 0
chout
couth
thuoc
touch


# Guessing

In [355]:
word = np.zeros(5) - 1
possible_letters = ['e','s','o','h','t']


#if position is known enter here
#word[0]= ord('t')-97
#word[1]= ord('h')-97
#word[2]= ord('')-97
#word[3]= ord('')-97
#word[4]= ord('')-97


known_lett_num = np.sum(word>-1)
tem_vec = np.zeros(known_lett_num)

len_letters = len(possible_letters)
possible_letters_vec = np.zeros(len_letters)

for i in range(len_letters):
    possible_letters_vec[i] = ord(possible_letters[i])-97

for i in range(len_letters-1):
    if (i==0):
        ls1 = (np.where(state_des[:,int(possible_letters_vec[i])] > 0)[0])
    
    ls2 = (np.where(state_des[:,int(possible_letters_vec[i+1])] > 0)[0])
    ls1 = np.intersect1d(ls1,ls2)

In [356]:
print("Printing all the words possible with the guess with positions")
for jj in range(ls1.shape[0]):
    a = []
    cnt = 0
    for i in lett_mat:
        if(np.all(i==state_des[ls1[jj]])):
            a.append(cnt)
        cnt+=1
    print("\n Anagram break, (1 state)")
    for k in a:
        if (np.sum(word)==-5):
            print(five_letter[k])
        else:
            known_letters = np.where(word>-1)[0]
            
            tem_vec = np.zeros(known_lett_num)
            for ii in range(known_lett_num):
                tem_vec[ii] = (ord(five_letter[k][known_letters[ii]])-97)
                if(np.all(word[known_letters] == tem_vec)):
                    print(five_letter[k])
                
        

Printing all the words possible with the guess with positions

 Anagram break, (1 state)
ethos
shote
theos
those


# Finding further orthogonal words given n guesses

In [ ]:
Guessed_words = ['spear','touch']

In [210]:
Guess_words_mat = np.zeros((len(Guessed_words),26))
cnt=0
for i in Guessed_words:
    for j in i:
        Guess_words_mat[cnt,ord(j)-97] += 1
    cnt+=1

In [212]:
Guess_words_mat

array([[1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 0., 1., 1., 0., 0., 0., 0., 0.]])

In [216]:
dot_states1 = (np.dot(state_des,Guess_words_mat[0,:].reshape(26,1))).reshape(state.shape[0])
dot_states2 = (np.dot(state_des,Guess_words_mat[1,:].reshape(26,1))).reshape(state.shape[0])

In [227]:
np.sum((dot_states1 == 0) * (dot_states2 == 0))

123

array([ True, False,  True, ..., False, False, False])

In [225]:
dot_states1 ==0

array([False, False, False, ..., False, False,  True])